---
- name : (Ubuntu) add cran apt key
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_key: keyserver='keyserver.ubuntu.com' id='E084DAB9'
  
- name: (Ubuntu) add cran apt repository
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_repository: repo='deb http://lib.stat.cmu.edu/R/CRAN/bin/linux/ubuntu trusty/' update_cache=yes
  
- name: (Ubuntu) installing R...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - r-base
    - r-base-dev
    - libcurl4-openssl-dev
    
- name: installing R packages...
  shell: R -e "install.packages(c('shiny', 'rmarkdown', 'dplyr'), repos='http://cran.rstudio.com/')"
  
- name: (Ubuntu) download R Studio
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  get_url: url={{rstudio_deb_url}} dest='/tmp/{{ rstudio_deb }}'
  
- name: (Ubuntu) install R Studio
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: deb='/tmp/{{ rstudio_deb }}'
