---
- name: download eclipse
  environment: proxy_env
  get_url: url={{ eclipse_url }} dest='/tmp/{{eclipse_archive}}'

- name: install eclipse
  unarchive: copy=no src='/tmp/{{eclipse_archive}}' dest='/opt'

- name: include eclipse in the default path...
  copy: src='etc/profile.d/eclipse.sh' dest='/etc/profile.d/eclipse.sh' mode=644
