---
- name: (Debian) editors packages...
  when: ansible_os_family == "Debian"
  apt: name={{item}}
  with_items:
    - vim

- name: (Fedora) editors packages ...
  when: ansible_distribution == "Fedora"
  yum: name={{item}}
  with_items:
    - vim

- name: (RedHat) editors packages ...
  when: ansible_distribution == "RedHat"
  yum: name={{ item }}
  with_items:
    - vim
