---
flink_ver : '0.8.1'
flink_hadoop_ver : 'hadoop2'
flink_name : 'flink-{{flink_ver}}'
flink_archive : '{{flink_name}}-bin-{{flink_hadoop_ver}}.tgz'
flink_url : 'http://mirror.reverse.net/pub/apache/flink/{{flink_name}}/{{flink_archive}}'