---
- hosts: localhost
  gather_facts: no
  roles:
    - {
    role: ec2-create-vm,
    uuid: "f3ca55e0-38b9-11e5-9c99-8851fb63ec99",
    instance_name: "burner-docker-vm",

    key_name: 'arothste',
    image: 'ami-96a818fe',
    }
