---
- hosts: all
  vars:
    go_version: 1.3.1
    go_archive: 'go{{ go_version }}.linux-amd64.tar.gz'
  tasks:
    - name: download go archive...
      get_url: url='https://storage.googleapis.com/golang/{{ go_archive }}' dest='/tmp/{{ go_archive }}'
    - name: install go...
      shell: tar -C /usr/local -xzf '/tmp/{{ go_archive }}'
    - name: set go environment variables
      lineinfile: dest=/etc/profile line='export PATH=$PATH:/usr/local/go/bin'