---
version: '3'
vars:
  CLUSTER_NAME: bootstrap
  ARGO_WORKFLOWS_NS: argo
  ARGO_WORKFLOWS_VER: 3.4.3
  ARGO_CD_NS: argocd
  ARGO_CD_VER: 2.5.2
  ARGO_ROLLOUTS_NS: argo-rollouts
  ARGO_ROLLOUTS_VER: 1.3.0
  GITEA_NS: gitea
  GITEA_NAME: gitea
  GITEA_CHART_REPO_NAME: gitea-charts
  GITEA_CHART_REPO_URL: https://dl.gitea.io/charts/
  GITEA_CHART: gitea
  GITEA_CHART_VER: 6.0.3
  HASHICORP_VAULT_NS: vault
  HASHICORP_VAULT_NAME: vault
  HASHICORP_CHART_REPO_NAME: hashicorp
  HASHICORP_CHART_REPO_URL: https://helm.releases.hashicorp.com
  HASHICORP_VAULT_CHART: vault
  HASHICORP_VAULT_CHART_VER: 0.23.0
  JETSTACK_CHART_REPO_NAME: jetstack
  JETSTACK_CHART_REPO_URL: https://charts.jetstack.io

tasks:
  argo-cd-apply:
    cmds:
      - task: kubectl-ns-create
        vars:
          n: '{{ .ARGO_CD_NS }}'
      - task: kubectl-apply
        vars:
          n: '{{ .ARGO_CD_NS }}'
          f: https://raw.githubusercontent.com/argoproj/argo-cd/v{{ .ARGO_CD_VER }}/manifests/install.yaml
  argo-cd-delete:
    cmds:
      - task: kubectl-delete
        vars:
          n: '{{ .ARGO_CD_NS }}'
          f: https://raw.githubusercontent.com/argoproj/argo-cd/v{{ .ARGO_CD_VER }}/manifests/install.yaml
      - task: kubectl-ns-delete
        vars:
          n: '{{ .ARGO_CD_NS }}'
  argo-workflows-apply:
    cmds:
      - task: kubectl-ns-create
        vars:
          n: '{{ .ARGO_WORKFLOWS_NS }}'
      - task: kubectl-apply
        vars:
          n: '{{ .ARGO_WORKFLOWS_NS }}'
          f: https://github.com/argoproj/argo-workflows/releases/download/v{{ .ARGO_WORKFLOWS_VER }}/install.yaml
  argo-workflows-delete:
    cmds:
      - task: kubectl-delete
        vars:
          n: '{{ .ARGO_WORKFLOWS_NS }}'
          f: https://github.com/argoproj/argo-workflows/releases/download/v{{ .ARGO_WORKFLOWS_VER }}/install.yaml
      - task: kubectl-ns-delete
        vars:
          n: '{{ .ARGO_WORKFLOWS_NS }}'
  argo-rollouts-apply:
    cmds:
      - task: kubectl-ns-create
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
      - task: kubectl-apply
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
          f: https://github.com/argoproj/argo-rollouts/releases/download/v{{ .ARGO_ROLLOUTS_VER }}/install.yaml
  argo-rollouts-delete:
    cmds:
      - task: kubectl-delete
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
          f: https://github.com/argoproj/argo-rollouts/releases/download/v{{ .ARGO_ROLLOUTS_VER }}/install.yaml
      - task: kubectl-ns-delete
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
  gitea-helm-repo-add:
    cmds:
      - task: helm-repo-add
        vars:
          CHART_REPO_NAME: '{{ .GITEA_CHART_REPO_NAME }}'
          CHART_REPO_URL: '{{ .GITEA_CHART_REPO_URL }}'
  gitea-helm-install:
    deps:
      - gitea-helm-repo-add
    cmds:
      - task: helm-install
        vars:
          NAMESPACE: '{{ .GITEA_NS }}'
          NAME: '{{ .GITEA_NAME }}'
          CHART_REPO_NAME: '{{ .GITEA_CHART_REPO_NAME }}'
          CHART: '{{ .GITEA_CHART }}'
          CHART_VER: '{{ .GITEA_CHART_VER }}'
  gitea-helm-delete:
    cmds:
      - task: helm-delete
        vars:
          NAMESPACE: '{{ .GITEA_NS }}'
          NAME: '{{ .GITEA_NAME }}'
  hashicorp-helm-repo-add:
    cmds:
      - task: helm-repo-add
        vars:
          CHART_REPO_NAME: '{{ .HASHICORP_CHART_REPO_NAME }}'
          CHART_REPO_URL: '{{ .HASHICORP_CHART_REPO_URL }}'
  hashicorp-vault-helm-install:
    cmds:
      - task: helm-install
        vars:
          NAMESPACE: '{{ .HASHICORP_VAULT_NS }}'
          NAME: '{{ .HASHICORP_VAULT_NAME }}'
          CHART_REPO_NAME: '{{ .HASHICORP_CHART_REPO_NAME }}'
          CHART: '{{ .HASHICORP_VAULT_CHART }}'
          CHART_VER: '{{ .HASHICORP_VAULT_CHART_VER }}'
  hashicorp-vault-helm-delete:
    cmds:
      - task: helm-delete
        vars:
          NAMESPACE: '{{ .HASHICORP_VAULT_NS }}'
          NAME: '{{ .HASHICORP_VAULT_NAME }}'
  chart-repos-add:
    deps:
      - gitea-helm-repo-add
      - hashicorp-helm-repo-add
  charts-install:
    deps:
      - gitea-helm-install
      - hashicorp-vault-helm-install
  charts-delete:
    deps:
      - gitea-helm-delete
      - hashicorp-vault-helm-delete
  charts-apply:
    deps:
      - chart-repos-add
      - charts-install
  apply:
    - task: argo-cd-apply
    - task: argo-workflows-apply
    - task: argo-rollouts-apply
    - task: chart-repos-add
    - task: charts-install
  delete:
    - task: charts-delete
    - task: argo-rollouts-delete
    - task: argo-workflows-delete
    - task: argo-cd-delete
