---
version: '3'
includes:
  ansible: tasks/ansible.yml
  k8s: tasks/k3d.yml
  istio: tasks/istio.yml
  argocd: tasks/argocd.yml
  argo: tasks/argo.yml
  argo-rollouts: tasks/argo-rollouts.yml
  gitea: tasks/gitea.yml
  hashicorp: tasks/hashicorp.yml
  jetstack: tasks/jetstack.yml
tasks:
  default:
    deps:
      - install-local-apps
  install-local-apps:
    internal: true
    deps:
      - ansible:playbook
  k8s-up:
    deps:
      - install-local-apps
    cmds:
      - task: k8s:up
  k8s-delete:
    deps:
      - install-local-apps
    cmds:
      - task: k8s:delete
  service-mesh-up:
    deps:
      - k8s-up
    cmds:
      - task: istio:up
  service-mesh-delete:
    deps:
      - install-local-apps
    cmds:
      - task: istio:delete
  up:
    deps:
      - service-mesh-up
    cmds:
      - task: argocd:apply
      - task: argo:apply
      - task: argo-rollouts:apply
      - task: gitea:install
      - task: hashicorp:vault-install
      - task: jetstack:install
  delete:
    deps:
      - jetstack:delete
      - hashicorp:vault-delete
      - gitea:delete
      - argo-rollouts:delete
      - argo:delete
      - argocd:delete
