---
- hosts: all
  vars:
    waf_version: 1.7.15
    waf_archive: 'waf-{{waf_version}}.tar.bz2'
    waf_target_dir: '/opt/waf-{{waf_version}}'
  tasks:
    - name: need bzip2
      apt: name=bzip2
    - name: download waf archive
      get_url: url='https://waf.googlecode.com/files/{{waf_archive}}' dest='/tmp/{{waf_archive}}'
    - name: install waf
      shell: tar -C /opt -jxvf '/tmp/{{waf_archive}}'
    - name: link waf
      file: src={{waf_target_dir}} dest=/opt/waf state=link
    - name: seed it
      shell: '{{waf_target_dir}}/waf --version'
      