---
- name: url related packages (Ubuntu)...
  when: ansible_distribution == "Ubuntu"
  apt: name={{item}}
  with_items:
    - traceroute
    - curl
    - wget
    - corkscrew

- name: url related packes (Fedora)
  when: ansible_distribution == "Fedora"
  yum: name={{item}}
  with_items:
    - traceroute
    - curl
    - wget
    - corkscrew
    