---
- name: (Red Hat) install puppetlabs repo
  when: ansible_distribution == "RedHat"
  environment: proxy_env
  yum: name='http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm' state=present

- name: (Red Hat, Fedora) install puppet
  when: ansible_distribution == "RedHat" or ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name={{item}}
  with_items:
    - puppet
