---
- name: create couchdb-lucene-data
  docker:
    name: couchdb-lucene-data
    image: andrewrothstein/couchdb-lucene:latest
    state: present
    volumes:
      - /opt/couchdb-lucene/indexes
      - /opt/couchdb-lucene/logs
    
- name: launch couchdb-lucene
  docker:
    name: couchdb-lucene
    image: andrewrothstein/couchdb-lucene:latest
    state: started
    ports:
      - "{{docker_couchdb_lucene_host_port}}:5985"
    volumes_from: couchdb-lucene-data

- name: create couchdb-data
  docker:
    name: couchdb-data
    image: andrewrothstein/couchdb:latest
    state: present
    volumes:
      - /usr/local/var/lib/couchdb
      - /usr/local/var/log/couchdb
    
- name: launch couchdb
  docker:
    name: couchdb
    image: andrewrothstein/couchdb:latest
    state: started
    ports:
      - "{{docker_couchdb_host_port}}:5984"
    volumes_from: couchdb-data