---
- name: (Ubuntu) install TeX
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-math-extra
    - texlive-tufte-latex
    - texlive-titlesec
    - texlive-units
    - texlive-lipsum