---
version: '3'
tasks:
  ansible-galaxy-install:
    sources:
      - requirements.yml
    cmds:
      - ansible-galaxy install -f -r requirements.yml
    generates:
      - .ansible-roles/**/*.yml
  ansible-playbook-localhost:
    deps:
      - ansible-galaxy-install
    cmds:
      - ansible-playbook --limit localhost --tag k8s-from-docker --tag k8s-gitops playbook.yml
      - echo done >> .onetime
    sources:
      - playbook.yml
    generates:
      - .onetime
