---
version: '3'
tasks:
  helm-repo-add:
    vars:
      CHART_REPO_NAME: '{{ default "my-charts" .CHART_REPO_NAME }}'
      CHART_REPO_URL: '{{ default "https://my-chart-museum/charts/" .CHART_REPO_URL }}'
    cmds:
      - helm repo add {{ .CHART_REPO_NAME }} {{ .CHART_REPO_URL }}
    status:
      - helm repo list -o json | jq -e '.[] | select(.name=={{ .CHART_REPO_NAME | quote }})'
  helm-install:
    vars:
      NAMESPACE: '{{ default "helm-install-namespace" .NAMESPACE }}'
      NAME: '{{ default "helm-release-name" .NAME }}'
      CHART_REPO_NAME: '{{ default "helm-chart-repo-nae" .CHART_REPO_NAME }}'
      CHART: '{{ default "helm-chart" .CHART }}'
      CHART_VER: '{{ default "helm-version-constraint" .CHART_VER }}'
    cmds:
      - task: kubectl-ns-create
        vars:
          n: '{{ .NAMESPACE }}'
      - helm install -n {{ .NAMESPACE }} {{ .NAME }} {{ .CHART_REPO_NAME }}/{{ .CHART }} --version {{ .CHART_VER }}
    status:
      - helm list -n {{ .NAMESPACE }} -o json | jq -e '.[] | select(.name=={{ .NAME | quote }})'
  helm-delete:
    vars:
      NAMESPACE: '{{ default "helm-install-namespace" .NAMESPACE }}'
      NAME: '{{ default "helm-release-name" .NAME }}'
    preconditions:
      - helm list -n {{ .NAMESPACE }} -o json | jq -e '.[] | select(.name=={{ .NAME | quote }})'
    cmds:
      - helm delete -n {{ .NAMESPACE }} {{ .NAME }}
