---
version: '3'
tasks:
  up:
    cmds:
      - kind create cluster -n {{ .CLUSTER_NAME }}
    status:
      - kind get clusters | grep {{ .CLUSTER_NAME }}
  delete:
    cmds:
      - kind delete clusters {{ .CLUSTER_NAME }}
