---
- name: (Ubuntu) get vagrant deb...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  get_url: url={{vagrant_deb_url}} dest='/tmp/{{ vagrant_deb }}'

- name: (Ubuntu) install vagrant deb
  when: ansible_distribution == "Ubuntu"
  apt: deb='/tmp/{{ vagrant_deb }}'

- name: (Fedora/RedHat) install vagrant rpm
  when: ansible_distribution == "Fedora" or ansible_distribution == "RedHat"
  environment: proxy_env
  yum: name='{{ vagrant_rpm_url }}' state=present

- name: (Fedora/RedHat) install vagrant-libvirt dependencies
  when: ansible_distribution == "Fedora" or ansible_distribution == "RedHat"
  environment: proxy_env
  yum: name={{item}} state=present
  with_items:
    - libxslt-devel
    - libxml2-devel
    - libvirt-devel
    - libguestfs-tools-c
  
- name: install vagrant plugins
  environment: proxy_env
  shell: vagrant plugin install {{item}}
  with_items:
    - vagrant-proxyconf
    - vagrant-hostsupdater
    - vagrant-cachier
    - vagrant-mutate
    - vagrant-libvirt

- name: (Fedora,RedHat) link exportfs into /usr/bin for vagrant
  when: ansible_distribution == "Fedora" or ansible_distribution == "RedHat"
  file: src='/usr/sbin/exportfs' dest='/usr/bin/exportfs' state=link

# firewall changes
#sudo firewall-cmd --zone=internal --change-interface=vboxnet0
#sudo firewall-cmd --permanent --zone=internal --add-service=nfs
#sudo firewall-cmd --permanent --zone=internal --add-service=rpc-bind
#sudo firewall-cmd --permanent --zone=internal --add-service=mountd
#sudo firewall-cmd --permanent --zone=internal --add-port=2049/udp
#sudo firewall-cmd --reload