---
- name: (Ubuntu) get vagrant deb...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  get_url: url={{vagrant_deb_url}} dest='/tmp/{{ vagrant_deb }}'

- name: (Ubuntu) install vagrant deb
  when: ansible_distribution == "Ubuntu"
  apt: deb='/tmp/{{ vagrant_deb }}'

- name: install vagrant proxyconf plugin
  environment: proxy_env
  shell: vagrant plugin install vagrant-proxyconf
