---
- name: download confd
  get_url: url=https://github.com/kelseyhightower/confd/releases/download/v0.6.3/confd-0.6.3-linux-amd64 dest=/usr/local/bin/confd
- name: chmod confd
  file: path=/usr/local/bin/confd mode=a+x