---
- name: install tar
  when: ansible_os_family == 'RedHat'
  yum: name={{item}} state=present
  with_items:
    - tar
    - unzip

- name: install tar
  when: ansible_os_family == 'Debian'
  apt: name={{item}} state=present
  with_items:
    - tar
    - unzip