---
- src: andrewrothstein.useraccounts
- src: andrewrothstein.proxify
- src: andrewrothstein.sudoers
- src: andrewrothstein.git
- src: andrewrothstein.go
- src: andrewrothstein.emacs
- src: andrewrothstein.galaxify
- src: andrewrothstein.hub
- src: andrewrothstein.nettools
- src: andrewrothstein.docker
- src: andrewrothstein.virtualbox
- src: andrewrothstein.vagrant
- src: andrewrothstein.mosh

