---

- name: (Ubuntu) get sbt deb...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  get_url: url=http://dl.bintray.com/sbt/debian/sbt-0.13.6.deb dest='/tmp/sbt-0.13.6.deb'

- name: (Ubuntu) install sbt deb...
  when: ansible_distribution == "Ubuntu"
  apt: deb=/tmp/sbt-0.13.6.deb state=installed

- name: (Ubuntu) install scala-mode2...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  copy: dest=/etc/emacs/site-start.d/ src=50scala-mode2.el

- name: (Ubuntu) install sbt-mode...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  copy: dest=/etc/emacs/site-start.d/ src=50sbt-mode.el

- name: (Fedora) install sbt...
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name=https://dl.bintray.com/sbt/rpm/sbt-0.13.6.rpm state=present
