---
- name: download intellij
  environment: proxy_env
  get_url: url={{ intellij_url }} dest='/tmp/{{intellij_archive}}'

- name: install intellij
  unarchive: copy=no dest='/opt' src='/tmp/{{intellij_archive}}'

- name: link /opt/intellij
  file: src='/opt/{{ intellij_subdir }}' dest=/opt/intellij state=link

- name: include intellij in the default path...
  copy: src='etc/profile.d/intellij.sh' dest='/etc/profile.d/intellij.sh' mode=644
