---
typesafe_activator_version : "1.2.12"
typesafe_activator_archive : "typesafe-activator-{{ typesafe_activator_version }}.zip"
typesafe_activator_url : "http://downloads.typesafe.com/typesafe-activator/{{ typesafe_activator_version }}/{{ typesafe_activator_archive }}"