---
- name: (Ubuntu) install saltstack ppa
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_repository: repo='ppa:saltstack/salt'

- name: install saltstack packages
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - salt-master
    - salt-minion
    - salt-syndic
    - salt-cloud
