---
- hosts: all
  vars:
    vault_ver: 1.12.1
  tags:
    - vault-cli
  roles:
    - andrewrothstein.vault
- hosts: all
  tags:
    - k8s-from-docker
  roles:
    - andrewrothstein.k3d
    - andrewrothstein.kind
    - andrewrothstein.kubectl
- hosts:
  - localhost
  tags:
    - k8s-sdn
  roles:
    - andrewrothstein.calicoctl
    - andrewrothstein.istio
- hosts:
  - localhost
  tags:
  - k8s-gitops
  roles:
    - andrewrothstein.git
    - andrewrothstein.jq
    - andrewrothstein.task
    - andrewrothstein.argocd
    - andrewrothstein.argo
    - andrewrothstein.kubeshark
    - andrewrothstein.kubernetes-helm
    - andrewrothstein.k9s
- hosts:
    - localhost
  tags:
    - go-cicd
  roles:
    - andrewrothstein.buildkit
    - andrewrothstein.go-dev
    - andrewrothstein.dagger
