---
- name: need bzip2
  apt: name=bzip2
- name: download waf archive
  get_url: url={{waf_archive_url}} dest='/tmp/{{waf_archive}}'
- name: install waf
  shell: tar -C /opt -jxvf '/tmp/{{waf_archive}}'
- name: link waf
  file: src={{waf_target_dir}} dest=/opt/waf state=link
- name: seed it
  shell: '{{waf_target_dir}}/waf --version'
      