---
- name: (Ubuntu) waf dependencies...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name=bzip2

- name: (Fedora) waf dependencis...
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name=bzip2

- name: download waf archive
  environment: proxy_env
  get_url: url={{ waf_archive_url }} dest='/tmp/{{waf_archive}}'
  
- name: install waf
  shell: tar -C /opt -jxvf '/tmp/{{waf_archive}}'
  
- name: link waf
  file: src={{waf_target_dir}} dest=/opt/waf state=link
  
- name: seed it
  shell: '{{waf_target_dir}}/waf --version'
