---
- name: (Ubuntu) file system related packages...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - sshfs
    - cifs-utils
    - samba
    - samba-common

- name: (Fedora) file system related packaged...
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name={{ item }}
  with_items:
    - sshfs
    - cifs-utils
    - samba
    - samba-common

