---
#unit_name : 'ansible-installed-hello-world.service'
#description : 'Hello World Service'
#image_name : 'busybox:latest'
#container_name : 'hello-world-busybox'
#docker_run_cmd : '/bin/sh -c "while true; do echo Hello World; sleep 1; done"'
#unit_install_dir : '/etc/systemd/system'
