---
- name: cpp dev packages (Ubuntu)...
  when: ansible_distribution == "Ubuntu"
  apt: name={{item}}
  with_items:
    - g++
    - gdb
    - graphviz
    - valgrind
    - cmake
    - libboost-dev
    - automake
    - kcachegrind
    - ccache
    - protobuf-compiler
    - libprotobuf-dev
    - doxygen
    - bison
    - flex
    - libbison-dev
    - libyaml-dev

- name: cpp dev packages (Fedora)...
  when: ansible_distribution == "Fedora"
  yum: name={{item}}
  with_items:
    - gcc-c++
    - gdb
    - graphviz
    - valgrind
    - cmake
    - boost
    - boost-devel
    - automake
    - kcachegrind
    - ccache
    - protobuf
    - protobuf-compiler
    - doxygen
    - bison
    - bison-devel
    - flex
    - flex-devel
    - libyaml
    - libyaml-devel
