---
- name: cpp dev packages...
  apt: name={{item}}
  with_items:
    - g++
    - gdb
    - graphviz
    - valgrind
    - cmake
    - libboost-dev
    - automake
    - kcachegrind
    - ccache
    - protobuf-compiler
    - libprotobuf-dev
    - doxygen
    - bison
    - libbison-dev
    - libyaml-dev