---
- name: create backing file from image file
  shell: qemu-img create -b {{image_file}} -o size={{disk}} -f {{instance_disk_fmt}} {{instance_disk_file}}

- name: build clouddrive
  include: 'clouddrive.yml'
  delegate_to: 127.0.0.1
  
- name: authorize root ssh keys
  shell: virt-copy-in -c qemu:///system -a {{backing_file}} ~/.ssh/authorized_keys /root/.ssh

- name: create instance definition
  template: src=instance.xml.j2 dest={{instance_file}}

- name: boot instance
  shell: virsh --connect qemu:///system create {{instance_file}}