---
- name: create /tmp/clouddrive_src_root
  file: >
    path={{clouddrive_src_root}}
    mode=700
    state=directory
  
- name: resolve the instance data templates
  with_items:
    - meta-data
    - user-data
  template: >
    src='{{clouddrive_template}}/{{item}}.j2'
    dest='{{clouddrive_src_root}}/{{item}}'

- name: build clouddrive
  shell: genisoimage -output '{{clouddrive_iso}}' -volid cidata -joliet -rock user-data meta-data
  args:
    chdir: '{{clouddrive_src_root}}'

- name: create backing file from image file
  shell: qemu-img create -b {{image_file}} -o size={{disk}} -f {{instance_disk_fmt}} {{instance_disk_file}}

- name: boot instance
  shell: >
    virt-install
    --connect {{connect_url}}
    --name {{instance_name}}
    --vcpus={{cpus}}
    --ram {{memory}}
    --disk path={{instance_disk_file}},device=disk,bus=virtio,format={{instance_disk_fmt}}
    --disk path={{clouddrive_iso}},device=cdrom,bus=virtio,format={{clouddrive_fmt}}
    --network=bridge=br-bond1,mac={{mac}},model=virtio
    --import
    --graphics none
    --noautoconsole