---
- name: (Ubuntu) add staticfloat/julia* ppas
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_repository: repo={{ item }}
  with_items:
    - ppa:staticfloat/juliareleases
    - ppa:staticfloat/julia-deps
  
- name: (Ubuntu) install julia
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name=julia

- name: install julia-mode
  copy: src=50julia-mode.el dest={{ emacs_site_d }}