---
- name: (Ubuntu) add staticfloat/julia* ppas
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_repository: repo={{ item }}
  with_items:
    - ppa:staticfloat/juliareleases
    - ppa:staticfloat/julia-deps
  
- name: (Ubuntu) install julia
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name=julia

- name: (Fedora) add julia yum repo
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  get_url: url='http://copr.fedoraproject.org/coprs/nalimilan/julia/repo/fedora-21/nalimilan-julia-fedora-21.repo' dest='/etc/yum.repos.d'

- name: (Fedora) install julia
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name=julia state=latest
  
- name: install julia-mode
  copy: src=50julia-mode.el dest={{ emacs_site_d }}