---
- name: (Ubuntu) web browsers...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - lynx
    - firefox
    - chromium-browser

- name: (Fedora) install google chrome
  when: ansible_distribution == "Fedora"
  copy: src=google-chrome.repo dest=/etc/yum.repos.d/google-chrome.repo owner=root group=root mode=644

- name: (Fedora) web browsers...
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name={{ item }}
  with_items:
    - lynx
    - firefox
    - google-chrome-stable
    - libexif
    - xauth
