---
docker_machine_ver : 'v0.4.1'
docker_machine_url : 'https://github.com/docker/machine/releases/download/{{docker_machine_ver}}/docker-machine_linux-amd64'
docker_machine_install_target : '/usr/local/bin/docker-machine-{{docker_machine_ver}}'
docker_machine_install_link : '/usr/local/bin/docker-machine'