---
- name: (Ubuntu) install vncserver
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - gnome-core
    - xfce4
    - firefox
    - vnc4server

- name: (Fedora) install vncserver
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name={{ item }}
  with_items:
    - tigervnc-server
