---
- name: (Ubuntu) virtualbox dependencies
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - dkms
    - libsdl-ttf2.0-0
    - libsdl1.2debian

- name : (Ubuntu) add virtualbox apt key
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_key: url='https://www.virtualbox.org/download/oracle_vbox.asc' id='98AB5139'

- name: (Ubuntu) add virtualbox apt repository
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' update_cache=yes

- name: (Ubuntu) install virtualbox
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name=virtualbox
