---
- name: (Ubuntu) virtualbox dependencies
  apt: name={{ item }}
  with_items:
    - dkms
    - libsdl-ttf2.0-0
    - libsdl1.2debian

- name : (Ubuntu) add virtualbox apt key
  apt_key: url='https://www.virtualbox.org/download/oracle_vbox.asc' id='98AB5139'

- name: add virtualbox apt repository
  apt_repository: >
    repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' update_cache=yes

- name: install virtualbox
  apt: name=VirtualBox-{{virtualbox_version}}


