---
- name: download go archive...
  get_url: url={{go_archive_url}} dest='/tmp/{{ go_archive }}'
- name: install go...
  shell: tar -C /usr/local -xzf '/tmp/{{ go_archive }}'
- name: set go environment variables
  lineinfile: dest=/etc/profile line='export PATH=$PATH:/usr/local/go/bin'