---
- name: download go archive...
  environment: proxy_env
  get_url: url={{go_archive_url}} dest='/tmp/{{ go_archive }}'
  
- name: install go...
  shell: tar -C /usr/local -xzf '/tmp/{{ go_archive }}'
  
- name: set go environment variables
  copy: src=go.sh dest=/etc/profile.d/go.sh mode=644
