---
- name: download terraform...
  get_url: url='{{ terraform_url }}' dest='/tmp/{{ terraform_zip }}'

- name: create /opt/terraform_version
  file: >
    owner=root
    group=root
    mode='go-w'
    path='/opt/{{ terraform_name }}'
    state=directory

  
- name: unarchive terraform...
  unarchive: copy=no src='/tmp/{{ terraform_zip }}' dest='/opt/{{ terraform_name }}'

- name: link /opt/terraform
  file: src='/opt/{{ terraform_name }}' dest='/opt/terraform' state=link

- name: include terraform-* in the default path...
  copy: src='etc/profile.d/terraform.sh' dest='/etc/profile.d/terraform.sh' mode=644