---
- name: Download spark archive...
  environment: proxy_env
  get_url: url='{{ spark_url }}' dest='/tmp/{{ spark_tgz }}'

- name: Install spark to /opt...
  unarchive: copy=no dest='/opt' src='/tmp/{{ spark_tgz }}'

- name: Linking /opt/spark
  file: src={{spark_target_dir}} dest=/opt/spark state=link
