---
- name: (Ubuntu) proxify apt...
  when: ansible_distribution == "Ubuntu" and (apt_http_proxy is defined or proxy_env.http_proxy is defined)
  environment: proxy_env
  template: src=95proxies.j2 dest=/etc/apt/apt.conf.d/95proxies