---
etcd_version: v2.1.1
etcd_name : 'etcd-{{ etcd_version }}-linux-amd64'
etcd_pkg : '{{ etcd_name }}.tar.gz'
etcd_pkg_url : 'http://github.com/coreos/etcd/releases/download/{{ etcd_version }}/{{ etcd_pkg }}'