---
- name : (Ubuntu) install docker.io package...
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name=docker.io state=present

- name : (Ubuntu) link docker to docker.io
  when: ansible_distribution == "Ubuntu"
  file: src=/usr/bin/docker.io dest=/usr/local/bin/docker state=link

- name : (Ubuntu) fix bash auto completion
  when: ansible_distribution == "Ubuntu"
  shell : sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io

- name : (Ubuntu) proxify
  when: ansible_distribution == "Ubuntu" and proxy_env.http_proxy is defined
  template: dest=/etc/default/docker.io src=etc/default/docker.io.j2

- name : (Fedora) install docker.io package...
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name=docker-io state=present

- name : (Fedora) launch docker...
  when: ansible_distribution == "Fedora"
  service: name=docker state=started

- name: (Fedora) update SELinux policy for docker
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name=selinux-policy state=latest

