---
- stat: path='/usr/bin/docker'
  register: dockerBinary

- name : download docker install script
  when: dockerBinary.stat.exists == false
  get_url: url='https://get.docker.com/' dest='/tmp/install.docker.sh'

- name: make install script executable
  when: dockerBinary.stat.exists == false
  file: path='/tmp/install.docker.sh' owner=root group=root mode=0755

- name: install docker
  when: dockerBinary.stat.exists == false
  shell: /tmp/install.docker.sh

- name : (Ubuntu) proxify
  when: ansible_distribution == "Ubuntu" and proxy_env.http_proxy is defined
  template: dest=/etc/default/docker src=etc/default/docker.j2

- name : (Fedora) proxify
  when: ansible_distribution == "Fedora" and proxy_env.http_proxy is defined
  template: dest=/etc/sysconfig/docker src=etc/sysconfig/docker-fedora.j2

- name : (RedHat) proxify
  when: ansible_distribution == "RedHat" and proxy_env.http_proxy is defined
  template: dest=/etc/sysconfig/docker src=etc/sysconfig/docker-redhat.j2

- name: (Fedora) update SELinux policy for docker
  when: ansible_distribution == "Fedora"
  yum: name=selinux-policy state=latest

- name : launch docker...
  service: name=docker state=restarted enabled=yes

- name: install docker-machine
  get_url: url='{{docker_machine_url}}' dest='{{docker_machine_install_target}}' mode=755

- name: link docker-machine
  file: src='{{docker_machine_install_target}}' dest='{{docker_machine_install_link}}' state=link
