---
- name : (Ubuntu) docker dependencies
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https

- name : (Ubuntu) add docker apt key
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_key: keyserver=keyserver.ubuntu.com id='36A1D7869245C8950F966E92D8576A8BA88D21E9'

- name: (Ubuntu) add docker apt repository
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' update_cache=yes

- name: (Ubuntu) install docker
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name=lxc-docker

- name : (Ubuntu) proxify
  when: ansible_distribution == "Ubuntu" and proxy_env.http_proxy is defined
  template: dest=/etc/default/docker src=etc/default/docker.j2

- name : (Fedora) install docker.io package...
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name=docker-io state=present

- name : (Fedora) launch docker...
  when: ansible_distribution == "Fedora"
  service: name=docker state=started

- name: (Fedora) update SELinux policy for docker
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name=selinux-policy state=latest

