---
- name: mkdir -p /etc/docker-registry/auth
  file: dest=/etc/docker-registry/auth owner=root group=root state=directory

- name: build /etc/docker-registry/auth/htpasswd
  shell: docker run --entrypoint htpasswd registry:2 -Bbn arothste password > /etc/docker-registry/auth/htpasswd
  args:
    creates: /etc/docker-registry/auth/htpasswd

- name : launching docker registry...
  docker :
    state: restarted
    name: 'registry'
    image: 'registry:2'
    ports:
      - "{{docker_registry_host_port}}:5000"
    volumes:
      - /etc/pki/tls/private:/keys
      - /etc/pki/tls/certs:/certs
      - /etc/docker-registry/auth:/auth
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE : /certs/{{inventory_hostname}}.crt
      REGISTRY_HTTP_TLS_KEY : /keys/{{inventory_hostname}}.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM : 'BLADE Docker Realm'
      REGISTRY_AUTH_HTPASSWD_PATH : /auth/htpasswd
      
      
