---
- name: create user arothste in groups admins,developers
  user: name=arothste state=present shell=/bin/bash groups=admins,developers 
- name: install arothste public key as authorized
  template: src=