---
# tasks file for mesos-servicerouter
- name: install ssl key
  copy: >-
    owner=root
    group=root
    mode=400
    src={{ssl_keys_dir}}/{{inventory_hostname}}.key
    dest={{target_ssl_keys_dir}}/{{inventory_hostname}}.key

- name: install certificate
  copy: >-
    owner=root
    group=root
    mode=400
    src={{ssl_certs_dir}}/{{inventory_hostname}}.crt.pem
    dest={{target_ssl_certs_dir}}/{{inventory_hostname}}.crt.pem

- name: install mesosphere.com.pem
  template: >-
    owner=root
    group=root
    mode=444
    src=etc/ssl/mesosphere.com.pem.j2
    dest={{target_ssl_certs_dir}}/mesosphere.com.pem

    